replicaCount: 1 

ingress: 
  host: solo-k8s.local 
  annotations: 
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"


GREETING: "Hello from beta canary"
