image:
  repository: beeruser/solo
  tag: 9d34de412c3197a17ce51aa7de6f9041d71dcccd
  pullPolicy: Always  

replicaCount: 3

service:
  port: 5000 
ingress:
  host: solo-k8s.local
  paths:
    - path: /
      pathType: Prefix
      # servicePort: 5000 
redis: 
  replicaCount: 2
  image:
    repository: redis
    tag: 9d34de412c3197a17ce51aa7de6f9041d71dcccd
  port: 6379

resources:
  requests:
    memory: "130Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

hpa: 
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  scaleUpPercent: 100
  scaleUpPeriodSeconds: 60
  scaleDownStabilizationWindowSeconds: 300
  scaleDownPercent: 100
  scaleDownPeriodSeconds: 60


GREETING: "Hello from ConfigMap"
